import {
  LayoutDashboard, Users, Building2,
  ClipboardList, TrendingDown, MessageSquare, FileText, History,
} from 'lucide-react';

export const MENU_ITEMS = [
  {
    id: 'dashboard',
    label: 'Dashboard',
    path: '/',
    icon: LayoutDashboard,
    color: 'from-cyan-500 to-cyan-600',
    lightBg: 'bg-cyan-50',
    iconColor: 'text-cyan-600',
  },
  {
    id: 'employees',
    label: 'Employees',
    path: '/employees',
    icon: Users,
    color: 'from-sky-500 to-sky-600',
    lightBg: 'bg-sky-50',
    iconColor: 'text-sky-600',
  },
  {
    id: 'departments',
    label: 'Departments',
    path: '/departments',
    icon: Building2,
    color: 'from-teal-500 to-teal-600',
    lightBg: 'bg-teal-50',
    iconColor: 'text-teal-600',
  },
  {
    id: 'attrition',
    label: 'Attrition',
    path: '/attrition',
    icon: TrendingDown,
    color: 'from-red-500 to-red-600',
    lightBg: 'bg-red-50',
    iconColor: 'text-red-500',
  },
  {
  id: 'exit-interviews', 
  label: 'Exit Interview',
  path: '/exit-interviews', 
  icon: ClipboardList,
  color: 'from-sky-500 to-sky-600',
  lightBg: 'bg-sky-50', 
  iconColor: 'text-sky-600',
},
  {
  id: 'concerns',
  label: 'Feedback',
  path: '/concerns',
  icon: MessageSquare,        
  color: 'from-violet-500 to-violet-600',
  lightBg: 'bg-violet-50',
  iconColor: 'text-violet-600',
},
  {
    id: 'audit-log',
    label: 'Audit Log',
    path: '/audit-log',
    icon: History, 
    color: 'from-slate-500 to-slate-600',
    lightBg: 'bg-slate-50',
    iconColor: 'text-slate-600',
  },
  {
  id: 'documents',
  label: 'Employee Documents',
  path: '/documents',
  icon: FileText,
  color: 'from-blue-500 to-blue-600',
  lightBg: 'bg-blue-50',
  iconColor: 'text-blue-600',
},

];